#!/bin/sh

RED='\033[0;31m'
NC='\033[0m' # No Color

display_help () {
    echo USAGE:
    echo "     submit [OPTION] <exercice name> <version> <message>"
    echo
    echo OPTIONS:
    echo "     -nc | --no-commit: submit will not commit your work"
    echo "     -m: different message for commit"
    echo "     -h | --help: display help"
}

behave () {
    commit=true
    commit_msg=
    while [ $# -gt 3 ]; do
        case $1 in
            -nc | --no-commit)
                commit=false
                ;;
            -m)
                shift
                commit_msg=$1
                ;;
            -* | --*)
                echo "Unknown option $1"
                display_help
                exit 1
        esac
        shift
    done

    exo_name=$1
    version=$2
    msg=$3

    if [ -z "$commit_msg" ]; then
        commit_msg=$msg
    fi

    if $commit; then
        echo -e "${RED}git add $exo_name${NC}"
        git add "$exo_name"
        if [ "$?" -ne 0 ]; then 
            exit 1 
        fi

        echo -e "${RED}git commit -m \"$commit_msg\"${NC}"
        if [ "$?" -ne 0 ]; then 
            exit 1 
        fi

        git commit -m "$commit_msg"
    fi

    echo -e "${RED}git tag -a \"exercises-${exo_name}-v$version\" -m \"$msg\"${NC}"
    git tag -a "exercises-${exo_name}v$version" -m "$msg"
    if [ "$?" -ne 0 ]; then 
        exit 1 
    fi

    echo -e "${RED}git push --follow-tags origin master${NC}"
    git push --follow-tags origin master
    if [ "$?" -ne 0 ]; then 
        exit 1 
    fi
}

if [ "$#" -eq 0 ]; then
    display_help
    exit 1
fi

case $1 in
    -h | --help)
        display_help
        exit
        ;;
    *)
        behave "$@"
esac
